# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'csdevs.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect, QRectF,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialog, QDialogButtonBox, QGraphicsView, QGroupBox,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QWidget)

class Ui_dlgCSDevs(object):
    def setupUi(self, dlgCSDevs):
        if not dlgCSDevs.objectName():
            dlgCSDevs.setObjectName(u"dlgCSDevs")
        dlgCSDevs.resize(467, 490)
        self.buttonBox = QDialogButtonBox(dlgCSDevs)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(30, 432, 407, 32))
        self.buttonBox.setLayoutDirection(Qt.LeftToRight)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(True)
        self.label = QLabel(dlgCSDevs)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 14, 56, 18))
        self.cbCameras = QComboBox(dlgCSDevs)
        self.cbCameras.setObjectName(u"cbCameras")
        self.cbCameras.setGeometry(QRect(68, 10, 389, 26))
        self.pbMonitor = QPushButton(dlgCSDevs)
        self.pbMonitor.setObjectName(u"pbMonitor")
        self.pbMonitor.setEnabled(False)
        self.pbMonitor.setGeometry(QRect(68, 42, 87, 26))
        self.lblWasDevnode = QLabel(dlgCSDevs)
        self.lblWasDevnode.setObjectName(u"lblWasDevnode")
        self.lblWasDevnode.setGeometry(QRect(120, 430, 150, 18))
        self.cbFormats = QComboBox(dlgCSDevs)
        self.cbFormats.setObjectName(u"cbFormats")
        self.cbFormats.setEnabled(False)
        self.cbFormats.setGeometry(QRect(65, 76, 120, 26))
        self.label_2 = QLabel(dlgCSDevs)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 53, 18))
        self.label_3 = QLabel(dlgCSDevs)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 108, 76, 18))
        self.lwFrameSizes = QListWidget(dlgCSDevs)
        self.lwFrameSizes.setObjectName(u"lwFrameSizes")
        self.lwFrameSizes.setEnabled(False)
        self.lwFrameSizes.setGeometry(QRect(88, 108, 140, 102))
        self.label_4 = QLabel(dlgCSDevs)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 381, 82, 18))
        self.leCapFile = QLineEdit(dlgCSDevs)
        self.leCapFile.setObjectName(u"leCapFile")
        self.leCapFile.setEnabled(False)
        self.leCapFile.setGeometry(QRect(94, 377, 335, 26))
        self.lblStatus = QLabel(dlgCSDevs)
        self.lblStatus.setObjectName(u"lblStatus")
        self.lblStatus.setGeometry(QRect(0, 470, 467, 18))
        self.label_5 = QLabel(dlgCSDevs)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(200, 348, 133, 18))
        self.sbNthFrame = QSpinBox(dlgCSDevs)
        self.sbNthFrame.setObjectName(u"sbNthFrame")
        self.sbNthFrame.setGeometry(QRect(339, 344, 50, 27))
        self.sbNthFrame.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sbNthFrame.setMinimum(1)
        self.sbNthFrame.setMaximum(999)
        self.sbNthFrame.setValue(40)
        self.label_6 = QLabel(dlgCSDevs)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 348, 104, 18))
        self.sbCapPeriod = QSpinBox(dlgCSDevs)
        self.sbCapPeriod.setObjectName(u"sbCapPeriod")
        self.sbCapPeriod.setGeometry(QRect(116, 344, 63, 27))
        self.sbCapPeriod.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sbCapPeriod.setMinimum(1)
        self.sbCapPeriod.setMaximum(3600)
        self.sbCapPeriod.setValue(60)
        self.label_7 = QLabel(dlgCSDevs)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(181, 348, 7, 18))
        self.cbControls = QComboBox(dlgCSDevs)
        self.cbControls.setObjectName(u"cbControls")
        self.cbControls.setEnabled(False)
        self.cbControls.setGeometry(QRect(68, 216, 191, 26))
        self.label_8 = QLabel(dlgCSDevs)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 220, 55, 18))
        self.groupBox = QGroupBox(dlgCSDevs)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 248, 447, 91))
        self.sbCtrlInt = QSpinBox(self.groupBox)
        self.sbCtrlInt.setObjectName(u"sbCtrlInt")
        self.sbCtrlInt.setEnabled(False)
        self.sbCtrlInt.setGeometry(QRect(6, 26, 62, 27))
        self.sbCtrlInt.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sbCtrlInt.setMaximum(9999)
        self.sbCtrlInt.setValue(0)
        self.lblCtrlIntMin = QLabel(self.groupBox)
        self.lblCtrlIntMin.setObjectName(u"lblCtrlIntMin")
        self.lblCtrlIntMin.setEnabled(False)
        self.lblCtrlIntMin.setGeometry(QRect(74, 30, 44, 18))
        self.lblCtrlIntMin.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.hsCtrlVal = QSlider(self.groupBox)
        self.hsCtrlVal.setObjectName(u"hsCtrlVal")
        self.hsCtrlVal.setEnabled(False)
        self.hsCtrlVal.setGeometry(QRect(121, 31, 273, 16))
        self.hsCtrlVal.setOrientation(Qt.Horizontal)
        self.lblCtrlIntMax = QLabel(self.groupBox)
        self.lblCtrlIntMax.setObjectName(u"lblCtrlIntMax")
        self.lblCtrlIntMax.setEnabled(False)
        self.lblCtrlIntMax.setGeometry(QRect(396, 30, 44, 18))
        self.cbCtrlVal = QCheckBox(self.groupBox)
        self.cbCtrlVal.setObjectName(u"cbCtrlVal")
        self.cbCtrlVal.setEnabled(False)
        self.cbCtrlVal.setGeometry(QRect(6, 59, 48, 24))
        self.lblCtrlOptions = QLabel(self.groupBox)
        self.lblCtrlOptions.setObjectName(u"lblCtrlOptions")
        self.lblCtrlOptions.setEnabled(False)
        self.lblCtrlOptions.setGeometry(QRect(74, 63, 111, 18))
        self.cbControlOptions = QComboBox(self.groupBox)
        self.cbControlOptions.setObjectName(u"cbControlOptions")
        self.cbControlOptions.setEnabled(False)
        self.cbControlOptions.setGeometry(QRect(187, 59, 254, 26))
        self.dayIcon = QGraphicsView(dlgCSDevs)
        self.dayIcon.setObjectName(u"dayIcon")
        self.dayIcon.setGeometry(QRect(234, 52, 223, 158))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dayIcon.sizePolicy().hasHeightForWidth())
        self.dayIcon.setSizePolicy(sizePolicy)
        self.dayIcon.setAcceptDrops(False)
        self.dayIcon.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.dayIcon.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.dayIcon.setSceneRect(QRectF(0, 0, 216, 158))
        self.pbSettings = QPushButton(dlgCSDevs)
        self.pbSettings.setObjectName(u"pbSettings")
        self.pbSettings.setGeometry(QRect(370, 216, 87, 26))
        self.lblImgQual = QLabel(dlgCSDevs)
        self.lblImgQual.setObjectName(u"lblImgQual")
        self.lblImgQual.setEnabled(False)
        self.lblImgQual.setGeometry(QRect(40, 405, 52, 18))
        self.hsImgQuality = QSlider(dlgCSDevs)
        self.hsImgQuality.setObjectName(u"hsImgQuality")
        self.hsImgQuality.setEnabled(False)
        self.hsImgQuality.setGeometry(QRect(94, 406, 337, 16))
        self.hsImgQuality.setMaximum(100)
        self.hsImgQuality.setValue(100)
        self.hsImgQuality.setOrientation(Qt.Horizontal)
        self.lblImgQuality = QLabel(dlgCSDevs)
        self.lblImgQuality.setObjectName(u"lblImgQuality")
        self.lblImgQuality.setEnabled(False)
        self.lblImgQuality.setGeometry(QRect(432, 405, 25, 18))
        self.pbDlgCapFile = QPushButton(dlgCSDevs)
        self.pbDlgCapFile.setObjectName(u"pbDlgCapFile")
        self.pbDlgCapFile.setGeometry(QRect(431, 377, 26, 26))
        QWidget.setTabOrder(self.cbCameras, self.pbMonitor)
        QWidget.setTabOrder(self.pbMonitor, self.cbFormats)
        QWidget.setTabOrder(self.cbFormats, self.lwFrameSizes)
        QWidget.setTabOrder(self.lwFrameSizes, self.cbControls)
        QWidget.setTabOrder(self.cbControls, self.sbCtrlInt)
        QWidget.setTabOrder(self.sbCtrlInt, self.hsCtrlVal)
        QWidget.setTabOrder(self.hsCtrlVal, self.cbCtrlVal)
        QWidget.setTabOrder(self.cbCtrlVal, self.cbControlOptions)
        QWidget.setTabOrder(self.cbControlOptions, self.sbCapPeriod)
        QWidget.setTabOrder(self.sbCapPeriod, self.sbNthFrame)
        QWidget.setTabOrder(self.sbNthFrame, self.leCapFile)
        QWidget.setTabOrder(self.leCapFile, self.hsImgQuality)
        QWidget.setTabOrder(self.hsImgQuality, self.pbDlgCapFile)
        QWidget.setTabOrder(self.pbDlgCapFile, self.pbSettings)
        QWidget.setTabOrder(self.pbSettings, self.dayIcon)

        self.retranslateUi(dlgCSDevs)
        self.buttonBox.accepted.connect(dlgCSDevs.accept)
        self.buttonBox.rejected.connect(dlgCSDevs.reject)

        QMetaObject.connectSlotsByName(dlgCSDevs)
    # setupUi

    def retranslateUi(self, dlgCSDevs):
        dlgCSDevs.setWindowTitle(QCoreApplication.translate("dlgCSDevs", u"CSDevs", None))
        self.label.setText(QCoreApplication.translate("dlgCSDevs", u"Camera:", None))
#if QT_CONFIG(tooltip)
        self.cbCameras.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Select which camera to use", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pbMonitor.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Access the camera and get it's features, e.g. controls, formats, etc.", None))
#endif // QT_CONFIG(tooltip)
        self.pbMonitor.setText(QCoreApplication.translate("dlgCSDevs", u"Monitor", None))
        self.lblWasDevnode.setText("")
#if QT_CONFIG(tooltip)
        self.cbFormats.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Select which of the camera's image formats to use (you must be monitoring a camera)", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("dlgCSDevs", u"Format:", None))
        self.label_3.setText(QCoreApplication.translate("dlgCSDevs", u"Resolution:", None))
#if QT_CONFIG(tooltip)
        self.lwFrameSizes.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Resolutions supported for a selected image format (you must be monitoring a camera). Select a resolution to start capture", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("dlgCSDevs", u"Capture file:", None))
#if QT_CONFIG(tooltip)
        self.leCapFile.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Filename to use for the captured image", None))
#endif // QT_CONFIG(tooltip)
        self.lblStatus.setText("")
        self.label_5.setText(QCoreApplication.translate("dlgCSDevs", u"Capture nth frames:", None))
#if QT_CONFIG(tooltip)
        self.sbNthFrame.setToolTip(QCoreApplication.translate("dlgCSDevs", u"How many frames to wait before capturing one (cameras often require several frames before the picture is stable)", None))
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("dlgCSDevs", u"Capture Period:", None))
#if QT_CONFIG(tooltip)
        self.sbCapPeriod.setToolTip(QCoreApplication.translate("dlgCSDevs", u"The time in seconds between capturing of images", None))
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("dlgCSDevs", u"s", None))
#if QT_CONFIG(tooltip)
        self.cbControls.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Select a camera control to see it's range and setting", None))
#endif // QT_CONFIG(tooltip)
        self.label_8.setText(QCoreApplication.translate("dlgCSDevs", u"Control:", None))
        self.groupBox.setTitle(QCoreApplication.translate("dlgCSDevs", u"Value", None))
#if QT_CONFIG(tooltip)
        self.sbCtrlInt.setToolTip(QCoreApplication.translate("dlgCSDevs", u"See, enter or adjust the value for a control with a number setting", None))
#endif // QT_CONFIG(tooltip)
        self.lblCtrlIntMin.setText(QCoreApplication.translate("dlgCSDevs", u"0", None))
#if QT_CONFIG(tooltip)
        self.hsCtrlVal.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Slide to adjust the current value of a control with a number setting", None))
#endif // QT_CONFIG(tooltip)
        self.lblCtrlIntMax.setText(QCoreApplication.translate("dlgCSDevs", u"0", None))
#if QT_CONFIG(tooltip)
        self.cbCtrlVal.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Click to change an ON/OFF camera control", None))
#endif // QT_CONFIG(tooltip)
        self.cbCtrlVal.setText(QCoreApplication.translate("dlgCSDevs", u"ON", None))
        self.lblCtrlOptions.setText(QCoreApplication.translate("dlgCSDevs", u"Control Options:", None))
#if QT_CONFIG(tooltip)
        self.pbSettings.setToolTip(QCoreApplication.translate("dlgCSDevs", u"Click to configure CSDevs", None))
#endif // QT_CONFIG(tooltip)
        self.pbSettings.setText(QCoreApplication.translate("dlgCSDevs", u"Settings", None))
        self.lblImgQual.setText(QCoreApplication.translate("dlgCSDevs", u"Quality:", None))
#if QT_CONFIG(tooltip)
        self.hsImgQuality.setToolTip(QCoreApplication.translate("dlgCSDevs", u"If the capture file format supports variable \"quality\", use the slider to make a quality choice", None))
#endif // QT_CONFIG(tooltip)
        self.lblImgQuality.setText(QCoreApplication.translate("dlgCSDevs", u"100", None))
        self.pbDlgCapFile.setText(QCoreApplication.translate("dlgCSDevs", u"...", None))
    # retranslateUi

